In [1]:
import tensorflow as tf
import IPython.display as display
import src.data.build_dataset as build_dataset
import importlib
import src.data.input_pipeline as input_pipeline

importlib.reload(build_dataset)
dataset_root = "D:\David\Škola\RP\dataset"
dataset_filename = "test_no_dup.json"

examples = build_dataset.process_dataset(dataset_root, dataset_filename, False)

print("Dataset processed")

Loaded 3076 items
Disposed 4 products
Disposed 0 outfits
Dataset processed


In [23]:
importlib.reload(input_pipeline)

for example in examples[:1]:
    parsed = input_pipeline.parse_example_with_images(example)
    print(parsed[0][0])
    # e = tf.io.parse_single_sequence_example(
    #     example, sequence_features={
    #         "categories": tf.io.FixedLenSequenceFeature([], tf.int64),
    #         "images": tf.io.FixedLenSequenceFeature([], tf.string)
    #     })
    # img = e[1]["images"][0].numpy()
    # display.display(display.Image(data=img))
    # print(e)

tf.Tensor(
[[[1.         1.         1.        ]
  [0.9996278  0.9996278  0.9996278 ]
  [0.99562323 0.99562323 0.99562323]
  ...
  [0.9963279  0.9963279  0.9963279 ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[0.9996278  0.9996278  0.9996278 ]
  [0.99493897 0.99493897 0.99493897]
  [0.99215686 0.99215686 0.99215686]
  ...
  [0.9963279  0.9963279  0.9963279 ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[0.9932624  0.9932624  0.9932624 ]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]
  ...
  [0.9963279  0.9963279  0.9963279 ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 ...

 [[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  ...
  [0.995829   0.995829   0.995829  ]
  [0.99215686 0.99215686 0.99215686]
  [0.99215686 0.99215686 0.99215686]]

 [[1.         1.         1.        ]
  [1.         1.         1

In [16]:
filenames = ["output.tfrecord"]
raw_dataset = tf.data.TFRecordDataset(filenames)

for raw_record in raw_dataset.take(1):
  example = tf.train.Example()
  print(repr(raw_record))
  example.ParseFromString(raw_record.numpy())
  print(example)

<tf.Tensor: id=122179, shape=(), dtype=string, numpy=b'\x12\x96\xc1\x03\nC\n\ncategories\x125\n\x06\x1a\x04\n\x02\x8f#\n\x05\x1a\x03\n\x01\x19\n\x05\x1a\x03\n\x01\x1b\n\x06\x1a\x04\n\x02\x85\x02\n\x06\x1a\x04\n\x02\x83\x02\n\x06\x1a\x04\n\x02\xaf\x0f\n\x05\x1a\x03\n\x01\x02\n\xcd\xc0\x03\n\x08features\x12\xbf\xc0\x03\n\x86@\x12\x83@\n\x80@IX\xb2;Ls\x8e>\xae^T<\x0f\x1d\x1e?m,\xc8=8\x94*>\x1bk\xeb<\xb6\x92\xe3<\x81O\x17?d\xbc\xe3?\x00\x00\x00\x00l\xc2\x19=\xd2\x82\xe7=\xd2\xac3=\xa6\xfe.>\xed\x81\x85;\xe5\x0b\x00?\xc8\xba\xc7=e\t\xcf?\xc1\xb5\xb0>\x1f\xf4\x19>20\x06?\x1b\xd7\x89?\xf50\x04=\xe9\x0eY>\xb6G\t?\xb3\xff\xa2>\xac!\xe0=\x86"y=\xae1\xfa;\x0f\x8a\xf2;\xaf!Y>\xfe<\xc6>3\x8e\xfb?h\xca\x10=\xb8\x81D>\xce\x93%?\x03t\x9b=\xc8G\x97=\x814\x1e?|6j>\x98\xf5]?\x1a7\xbf?\xe2\xe3\x8e=\x96K\x93?_\xce\x0e<\x98\xc1\xa5>\rd\x85>\xba\x12\xb2>\xfc2O<T\xd2h>\xe4(%>J\xba\x9f>\x9a\xc1\xd3>\x00\x00\x00\x00\xe9\xd8\x89>H\x14B>\x8a\x9d\x8b?~\x9c\xbc=n\xee\x81?\xfd-\x07>\xc5*Q=\xb5\x04\xc4;3h\x8c<\xbb\xd

In [18]:
filenames = ["output-000-5.tfrecord"]
raw_dataset = tf.data.TFRecordDataset(filenames)

for raw_record in raw_dataset.take(1):
  example = tf.io.parse_single_sequence_example(
      raw_record.numpy(), sequence_features= {
          "categories": tf.io.FixedLenSequenceFeature([], tf.int64),
          "features": tf.io.FixedLenSequenceFeature(2048,tf.float32)
      })
  print(example)

({}, {'categories': <tf.Tensor: id=122232, shape=(7,), dtype=int64, numpy=array([4495,   25,   27,  261,  259, 1967,    2], dtype=int64)>, 'features': <tf.Tensor: id=122233, shape=(7, 2048), dtype=float32, numpy=
array([[0.00544265, 0.2782234 , 0.01296203, ..., 0.03073396, 0.02102465,
        0.60515   ],
       [0.10327241, 0.59317654, 0.23712789, ..., 0.5107244 , 0.32906044,
        0.2647133 ],
       [0.04759569, 0.24221316, 0.03452357, ..., 0.4702158 , 0.04748438,
        0.21493322],
       ...,
       [0.1191927 , 0.5459111 , 0.11253152, ..., 0.12103943, 0.02401951,
        0.4204527 ],
       [0.80003095, 0.6951431 , 0.6862365 , ..., 0.28535375, 0.02023683,
        0.32046562],
       [1.0514071 , 0.        , 0.        , ..., 0.04131878, 0.7136081 ,
        2.0880868 ]], dtype=float32)>})


In [3]:
files_per_dataset = 16
outfits_per_file = len(examples) // files_per_dataset

if len(examples) % files_per_dataset > 0:
    outfits_per_file = outfits_per_file + 1

for i in range(len(examples)):
    if i % outfits_per_file == 0:
        if i != 0:
            writer.close()
        writer = tf.io.TFRecordWriter(r"D:\David\Škola\outfit-generation\data\processed\tfrecords\train-{0:03}-{1}.tfrecord".format(i // outfits_per_file, files_per_dataset))
    writer.write(examples[i])
    if i == len(examples):
        writer.close()