In [40]:
import tensorflow as tf
from IPython import display
import src.data.input_pipeline as input_pipeline

tf.config.experimental_run_functions_eagerly(True) 

# dataset = input_pipeline.get_dataset(
#     [r"D:\David\Škola\outfit-generation\data\processed\tfrecords\debug-cleaned-raw-000-1.tfrecord"], 
#     False)

raw_dataset = tf.data.TFRecordDataset([r"D:\David\Škola\outfit-generation\data\processed\tfrecords\debug-cleaned-raw-000-1.tfrecord"])

def decode_img(img):
    # convert the compressed string to a 3D uint8 tensor
    img = tf.image.decode_jpeg(img, channels=3)
    return tf.keras.applications.inception_v3.preprocess_input(tf.image.resize(img, [299, 299]))



def parse_example_with_images(raw):
    example = tf.io.parse_single_sequence_example(
        raw, sequence_features={
            "categories": tf.io.FixedLenSequenceFeature([], tf.int64),
            "images": tf.io.FixedLenSequenceFeature([], tf.string)
        })
    
    raw_imgs = example[1]["images"]
    
    res = tf.map_fn(decode_img, raw_imgs, dtype=tf.float32)

    return res, example[1]["categories"]


def build():
    dataset = raw_dataset.take(1).map(parse_example_with_images)
    for item in dataset:
        print(item[0][0])
        img = tf.keras.preprocessing.image.array_to_img(item[0][0])
        img.show()
        print("smth")
        break

build()

tf.Tensor(
[[[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [0.9996065 0.9996065 0.9996065]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [0.9996065 0.9996065 0.9996065]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [0.9996065 0.9996065 0.9996065]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 ...

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [0.9996065 0.9996065 0.9996065]
  [1.        1.        1.       ]
  [1.        1.        1.       ]]

 [[1.        1.        1.       ]
  [1.        1.        1.       ]
  [1.        1.        1.       ]
  ...
  [0.9996065 0.9996065 0.99