In [93]:
import random
from typing import Tuple
import tensorflow as tf



# test_tensor = tf.constant([1,2,3,0,1,1,0,3,3,0,0,0], shape=(2,2,3), dtype="float32")
# print(test_tensor)
# indices = tf.constant([[0,0]])
# updates = tf.constant([[9,9,9]], dtype="float32")
# test_tensor = tf.tensor_scatter_nd_update(test_tensor,indices,updates)
# print(test_tensor)


def parse_example(raw):
    example = tf.io.parse_single_sequence_example(
          raw, sequence_features={
              "categories": tf.io.FixedLenSequenceFeature([], tf.int64),
              "features": tf.io.FixedLenSequenceFeature(2048, tf.float32)
          })
    return example[1]["features"], example[1]["categories"]


def get_dataset(filenames):
    raw_dataset = tf.data.TFRecordDataset(filenames)
    return raw_dataset.map(parse_example)


def append_targets(features, categories, token_pos):
    return (features, categories, token_pos), features


def add_special_token_positions(features, categories):
    seq_length = tf.shape(categories)[0]
    random_position = tf.random.uniform((1,), minval=0, maxval=seq_length, dtype="int32")
    token_positions = tf.expand_dims(random_position, 0)
    return features, categories, token_positions
    
    
def get_training_dataset(filenames, batch_size):
    outfits = get_dataset(filenames)
    outfits = outfits.map(add_special_token_positions)
    outfits = outfits.padded_batch(batch_size, ([None, 2048], [None], [None,1]))
    return outfits.map(append_targets)


def replace_slices(batch, batched_positions, updates):
    """

    Args:
        batch: Tensor of shape [batch_size, seq_length, feature_dim]
        batched_positions: Tensor of shape [batch_size, None, 1] corresponding to indices of sequence
        updates: Tensor of shape [total_number_of_indices, feature_dim]

    Returns:
        Tensor with the same shape as batch. Defined slices are replaced
    """
    batch_size = tf.shape(batched_positions)[0]
    r = tf.range(0, limit=batch_size, dtype="int32")
    r = tf.reshape(r, shape=[tf.shape(r)[0], -1, 1])
    indices = tf.squeeze(tf.concat([r, batched_positions], axis=-1))
    print(indices)
    return tf.tensor_scatter_nd_update(batch, indices, updates)


batch = tf.range(0, 24)
batch = tf.reshape(batch, [2, 3, 4])
b_pos = tf.constant([[[0]], [[2]]])
up = tf.constant([[8, 8, 8, 8], [9, 9, 9, 9]])
print(batch)
res = replace_slices(batch, b_pos, up)
print(res)


tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[ 8  8  8  8]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [ 9  9  9  9]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
dataset = get_training_dataset(["output-000-5.tfrecord"], 2)

# for x, y in dataset:
#     zeroes = tf.meshgrid(tf.range(tf.shape(x[0])[0]), tf.range(tf.shape(x[0])[0]))
#     mask_positions = x[2]
#     zero_slices = tf.gather_nd(zeroes, x[2], batch_dims=1)
#     updates = tf.reshape(zero_slices, shape=(-1, 2048))
#     print(x[2])
#     r = tf.range(0, limit=tf.shape(x[2])[0], dtype="int32")
#     r = tf.reshape(r, shape=[r.shape[0], -1, 1])
#     print(r)
#     indices = tf.squeeze(tf.concat([r, x[2]], axis=-1))
#     print(indices)
#     # indices = tf.constant([[0,1], [1, 6]]) 
#     replaced = tf.tensor_scatter_nd_update(x[0], indices, updates)
#     print(replaced)
# 
#     r = tf.range(0, limit=tf.shape(mask_positions)[0], dtype="int64")
#     r = tf.reshape(r, shape=[tf.shape(r)[0], -1, 1])
#     mask_positions = tf.cast(mask_positions, dtype="int64")
#     indices = tf.squeeze(tf.concat([r, mask_positions], axis=-1))
#     weights = tf.sparse.to_dense(tf.SparseTensor(indices, 1, dense_shape=tf.cast(tf.shape(y), dtype="int64")))
#     weights = tf.reshape(weights, [-1])
#     print(weights)
    
    
    # r = tf.range(0, limit=tf.shape(mask_positions)[0])
    # r = tf.reshape(r, shape=[tf.shape(r)[0], -1, 1])
    # indices = tf.squeeze(tf.concat([r, mask_positions], axis=-1))
    # print(indices)
    # updates = tf.ones(shape=(tf.shape(mask_positions)[0]))
    # print(updates)
    # weights = tf.scatter_nd(indices, updates, tf.shape(x[1]))
    # weights = tf.cast(weights, dtype="float32")
    # weights = tf.reshape(weights, [-1])
    # length = tf.shape(weights)[0]
    # weights = tf.tile(weights, [length])
    # weights = tf.reshape(weights, [-1, length])
    # weights = tf.transpose(weights)
    # print(weights)
    

In [8]:
import tensorflow as tf

def xentropy_loss(y_pred, y_true, categories, mask_positions, acc=None):
    feature_dim = y_pred.shape[2]

    # Compute loss only from mask token
    r = tf.range(0, limit=tf.shape(mask_positions)[0])
    r = tf.reshape(r, shape=[tf.shape(r)[0], -1, 1])
    indices = tf.squeeze(tf.concat([r, mask_positions], axis=-1))
    updates = tf.ones(shape=(tf.shape(mask_positions)[0]))
    weights = tf.scatter_nd(indices, updates, tf.shape(categories))
    weights = tf.cast(weights, dtype="float32")
    weights = tf.reshape(weights, [-1])
    weights_sum = tf.reduce_sum(weights)
    print(weights)
    print(weights_sum)

    # Reshape to batch (size * seq length, feature dim)
    pred_batch = tf.reshape(y_pred, [-1, feature_dim])
    true_batch = tf.reshape(y_true, [-1, feature_dim])
    item_count = true_batch.shape[0]
    print(pred_batch)

    # Dot product of every prediction with all labels
    logits = tf.matmul(pred_batch, true_batch, transpose_b=True)
    print(logits)
    
    # One-hot labels (the indentity matrix)
    labels = tf.eye(item_count, item_count)

    # Compute weights to identify padding values
    # not_padded = tf.equal(true_batch, 0)
    # not_padded = tf.reduce_all(not_padded, axis=1)
    # not_padded = tf.math.logical_not(not_padded)
    # not_padded = tf.cast(not_padded, dtype="float32")
    # items_in_batch = tf.reduce_sum(not_padded)

    if acc is not None:
        acc(labels, logits, sample_weight=weights)

    cross_entropy = tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=logits)
    print(cross_entropy)
    cross_entropy = tf.tensordot(cross_entropy, weights, 1)
    print(cross_entropy)
    return tf.reduce_sum(cross_entropy) / weights_sum

acc = tf.keras.metrics.CategoricalAccuracy()
batch = tf.range(0, 24, dtype="float32")
batch_pred = tf.reshape(batch, [2, 3, 4])
cat = tf.zeros(shape=[2,3], dtype="float32")
b_pos = tf.constant([[[0]], [[1]]])

xentropy_loss(batch_pred, batch_pred, cat, b_pos,acc)

tf.Tensor([1. 0. 0. 0. 1. 0.], shape=(6,), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]], shape=(6, 4), dtype=float32)
tf.Tensor(
[[  14.   38.   62.   86.  110.  134.]
 [  38.  126.  214.  302.  390.  478.]
 [  62.  214.  366.  518.  670.  822.]
 [  86.  302.  518.  734.  950. 1166.]
 [ 110.  390.  670.  950. 1230. 1510.]
 [ 134.  478.  822. 1166. 1510. 1854.]], shape=(6, 6), dtype=float32)
tf.Tensor([120. 352. 456. 432. 280.   0.], shape=(6,), dtype=float32)
tf.Tensor(400.0, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=200.0>