In [7]:
import tensorflow as tf

def generate_mask_categories(categories, mask_positions):
    mask_positions = tf.squeeze(mask_positions, axis=[1])
    mask_categories = tf.gather_nd(categories, mask_positions, batch_dims=1)
    mask_categories = tf.expand_dims(mask_categories, axis=1)
    mask_categories = tf.tile(mask_categories, [1, tf.shape(categories)[1]])
    return mask_categories

    
mask = tf.constant([[[0]], [[2]], [[3]]], dtype=tf.int32)
categories = tf.constant([1,2,4,1,4,1,2,3,2,5,1,4], shape=(3,4))

generate_mask_categories(categories, mask)


tf.Tensor(
[[1]
 [2]
 [4]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [2 2 2 2]
 [4 4 4 4]], shape=(3, 4), dtype=int32)
