In [1]:
import models.transformer.fashion_transformer as fashion_t
import models.transformer.fashion_encoder as fashion_enc
import official.transformer.v2.misc as misc
import importlib
import tensorflow as tf
import src.models.transformer.metrics as metrics

In [15]:
importlib.reload(fashion_enc)

params = misc.get_model_params("base", 1)

params.update({
    "feature_dim": 2048,
    "dtype": "float32",
    "hidden_size": 512,
    "extra_decode_length": 0,
    "num_hidden_layers": 1,
    "num_heads": 2,
    "max_length": 10,
    "default_batch_size": 128,
    "filter_size": 1024
})

model = fashion_enc.create_model(params, False)
model.summary()

Before dense
(None, None, 2048)
After dense
(None, None, 512)
Model: "transformer_v2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, None, 512)         1049088   
_________________________________________________________________
dense_1 (Dense)              (None, None, 2048)        1050624   
_________________________________________________________________
encoder_stack_9 (EncoderStac (None, None, 512)         2101760   
Total params: 4,201,472
Trainable params: 4,201,472
Non-trainable params: 0
_________________________________________________________________
Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, None, 2048)]      0         
_________________________________________________________________
transformer_v2 (FashionEncod 

In [16]:
input_batch = tf.random.uniform(shape=(3,2,2048))
output = model.predict_on_batch(input_batch)
print(output.shape)
print(output)
model.summary()

(3, 2, 2048)
[[[5.3061867e-01 0.0000000e+00 0.0000000e+00 ... 9.8705864e-01
   3.0908227e-02 0.0000000e+00]
  [8.4564286e-01 0.0000000e+00 0.0000000e+00 ... 1.5424176e+00
   3.2188863e-01 0.0000000e+00]]

 [[7.1251291e-01 3.5658669e-01 0.0000000e+00 ... 1.1799755e+00
   9.2774630e-05 0.0000000e+00]
  [1.1838869e+00 7.3470104e-01 0.0000000e+00 ... 1.3230802e+00
   0.0000000e+00 0.0000000e+00]]

 [[7.9162467e-01 3.8026094e-01 0.0000000e+00 ... 9.5547354e-01
   7.4496865e-02 0.0000000e+00]
  [0.0000000e+00 5.8710259e-01 0.0000000e+00 ... 1.4925238e+00
   0.0000000e+00 0.0000000e+00]]]
Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, None, 2048)]      0         
_________________________________________________________________
transformer_v2 (FashionEncod (None, None, 2048)        4201472   
Total params: 4,201,472
Trainable params: 4,201,472
Non-trainabl

In [4]:
importlib.reload(fashion_t)

params = misc.get_model_params("base", 1)

params.update({
    "feature_dim": 2048,
    "dtype": "float32",
    "hidden_size": 512,
    "extra_decode_length": 0,
    "num_hidden_layers": 1,
    "num_heads": 2,
    "max_length": 10,
    "default_batch_size": 128,
    "filter_size": 1024
})

model = fashion_t.create_model(params, False)
model.summary()

inputs
(None, None, 2048)
attention_bias
(None, 1, 1, None)


ValueError: in converted code:
    relative to D:\:

    avid\Škola\outfit-generation\src\models\transformer\fashion_transformer.py:150 call  *
        encoder_outputs = self.encode(inputs, attention_bias, training)
    avid\Škola\outfit-generation\src\models\transformer\fashion_transformer.py:195 encode  *
        return self.encoder_stack(
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py:842 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    avid\Škola\outfit-generation\src\models\transformer\fashion_transformer.py:518 call  *
        encoder_inputs = self_attention_layer(
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py:842 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    avid\Škola\outfit-generation\src\models\transformer\fashion_transformer.py:453 call  *
        return x + y
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\ops\math_ops.py:899 binary_op_wrapper
        return func(x, y, name=name)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\ops\math_ops.py:1197 _add_dispatch
        return gen_math_ops.add_v2(x, y, name=name)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py:549 add_v2
        "AddV2", x=x, y=y, name=name)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\framework\op_def_library.py:793 _apply_op_helper
        op_def=op_def)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\framework\func_graph.py:548 create_op
        compute_device)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\framework\ops.py:3429 _create_op_internal
        op_def=op_def)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\framework\ops.py:1773 __init__
        control_input_ops)
    rogramy\Anaconda3\envs\outfit-generation\lib\site-packages\tensorflow_core\python\framework\ops.py:1613 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 2048 and 512 for 'transformer_v2_1/Transformer/encode/encoder_stack_1/layer_0/self_attention/pre_post_processing_wrapper_5/add' (op: 'AddV2') with input shapes: [?,?,2048], [?,?,512].


In [4]:
input_batch = tf.random.uniform(shape=(25,8,256))

output = model.predict_on_batch(input_batch)

print(output.shape)
print(output)

(25, 8, 256)
[[[ 0.3721342   0.7154289  -0.06266356 ...  0.7965158  -0.33333158
   -0.73048675]
  [ 0.3721342   0.7154289  -0.06266356 ...  0.7965158  -0.33333158
   -0.73048675]
  [ 0.3721342   0.7154289  -0.06266356 ...  0.7965158  -0.33333158
   -0.73048675]
  ...
  [ 0.3721342   0.7154289  -0.06266356 ...  0.7965158  -0.33333158
   -0.73048675]
  [ 0.3721342   0.7154289  -0.06266356 ...  0.7965158  -0.33333158
   -0.73048675]
  [ 0.3721342   0.7154289  -0.06266356 ...  0.7965158  -0.33333158
   -0.73048675]]

 [[ 0.80776685  0.04199074 -1.3678492  ...  0.13974936 -1.3057268
   -1.5029002 ]
  [ 0.80776685  0.04199074 -1.3678492  ...  0.13974936 -1.3057268
   -1.5029002 ]
  [ 0.80776685  0.04199074 -1.3678492  ...  0.13974936 -1.3057268
   -1.5029002 ]
  ...
  [ 0.80776685  0.04199074 -1.3678492  ...  0.13974936 -1.3057268
   -1.5029002 ]
  [ 0.80776685  0.04199074 -1.3678492  ...  0.13974936 -1.3057268
   -1.5029002 ]
  [ 0.80776685  0.04199074 -1.3678492  ...  0.13974936 -1.3057268

In [2]:
# Dimension reduction before padding

#tensorflow Shape (batch, input_length, feature_dim)
test_tensor = tf.constant([1,2,3,0,1,1,0,3,3,0,0,0], shape=(2,2,3), dtype="float32")
print(test_tensor)
test_tensor = tf.equal(test_tensor,0)
print(test_tensor)
test_tensor = tf.reduce_all(test_tensor, axis=2)
print(test_tensor)
test_tensor = tf.math.logical_not(test_tensor)
print(test_tensor)
test_tensor = tf.cast(test_tensor, dtype="int32")
print(test_tensor)
test_tensor = tf.reduce_sum(test_tensor)
print(test_tensor)

tf.Tensor(
[[[1. 2. 3.]
  [0. 1. 1.]]

 [[0. 3. 3.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor(
[[[False False False]
  [ True False False]]

 [[ True False False]
  [ True  True  True]]], shape=(2, 2, 3), dtype=bool)
tf.Tensor(
[[False False]
 [False  True]], shape=(2, 2), dtype=bool)
tf.Tensor(
[[ True  True]
 [ True False]], shape=(2, 2), dtype=bool)
tf.Tensor(
[[1 1]
 [1 0]], shape=(2, 2), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [14]:
importlib.reload(metrics)

#tensorflow Shape (batch, input_length, feature_dim)
pred = tf.constant([1,2,3,0,1,1,0,3,3,0,0,0], shape=(2,2,3), dtype="float32")
true = tf.constant([1,2,3,0,1,1,0,3,3,0,0,0], shape=(2,2,3), dtype="float32")

loss = metrics.categorical_acc(pred,true)

print(loss)

# pred = tf.constant([1,0,0,0,0,1,0,3,0,0,0,0], shape=(2,2,3), dtype="float32")
# true = tf.constant([1,0,0,0,0,1,0,3,0,0,0,0], shape=(2,2,3), dtype="float32")
# 
# loss = metrics.categorical_acc(pred,true)
# 
# print(loss)

tf.Tensor(
[[14.  5. 15.  0.]
 [ 5.  2.  6.  0.]
 [15.  6. 18.  0.]
 [ 0.  0.  0.  0.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[False False False]
 [ True False False]
 [ True False False]
 [ True  True  True]], shape=(4, 3), dtype=bool)
tf.Tensor([False False False  True], shape=(4,), dtype=bool)
tf.Tensor([ True  True  True False], shape=(4,), dtype=bool)
tf.Tensor([1. 1. 1. 0.], shape=(4,), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(0.33333334, shape=(), dtype=float32)
