In [6]:
import models.transformer.fashion_transformer as fashion_t
import official.transformer.v2.misc as misc
import importlib

import tensorflow as tf

importlib.reload(fashion_t)

params = misc.get_model_params("base", 1)

params.update({
    "feature_dim": 256,
    "dtype": "float32",
    "hidden_size": 256,
    "extra_decode_length": 0,
    "num_hidden_layers": 1,
    "num_heads": 2,
    "max_length": 10,
    "default_batch_size": 128,
    "filter_size": 1024
})

model = fashion_t.create_model(params, False)
model.summary()

inputs
(None, None, 256)
attention_bias
(None, 1, 1, None)
(None, None, 2, 128)
(None, None, 2, 128)
(None, 2, None, None)
(None, 2, None, None)
(None, 2, None, None)
(None, None, 2, 128)
(25, 1, 2, 128)
(25, 1, 2, 128)
(25, 2, 1, 1)
(25, 2, 1, 1)
(25, 2, 1, 1)
(25, 1, 2, 128)
(None, None, 2, 128)
(25, 1, 2, 128)
(None, 2, 1, None)
(None, 2, 1, None)
(None, 2, 1, None)
(None, None, 2, 128)
Model: "transformer_v2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
encoder_stack_4 (EncoderStac (None, None, 256)         789248    
_________________________________________________________________
decoder_stack_4 (DecoderStac multiple                  1051904   
Total params: 1,841,152
Trainable params: 1,841,152
Non-trainable params: 0
_________________________________________________________________
Model: "model_4"
_________________________________________________________________
Layer (type)                

In [12]:
input_batch = tf.random.uniform(shape=(25,8,256))

output = model.predict_on_batch(input_batch)

print(output.shape)
print(output)

(25, 1, 256)
[[[-0.5820612   1.8437483  -0.41871476 ...  0.1081553  -1.0700114
    0.5742912 ]]

 [[-0.14290895  2.2447252  -0.604621   ...  1.0364529  -0.84680265
    0.47821474]]

 [[-0.5845432   1.9734398  -0.973502   ...  1.0592749  -0.07056158
    0.7728396 ]]

 ...

 [[-0.88227975  2.3817751  -0.54287994 ...  0.75385416 -0.43158063
    0.6333025 ]]

 [[-0.94250876  1.6431019   0.05301608 ...  0.95952725 -0.5512805
    0.28709587]]

 [[-0.8383326   2.1202738  -0.93100446 ... -0.0190403  -0.8832363
    0.38850668]]]


In [11]:
# Dimension reduction before padding

#tensorflow Shape (batch, input_length, feature_dim)
test_tensor = tf.constant([1,2,3,0,1,1,0,3,3,0,0,0], shape=(2,2,3), dtype="float32")
print(test_tensor)
test_tensor = tf.equal(test_tensor,0)
print(test_tensor)
test_tensor = tf.reduce_all(test_tensor, axis=2)
print(test_tensor)

tf.Tensor(
[[[1. 2. 3.]
  [0. 1. 1.]]

 [[0. 3. 3.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor(
[[[False False False]
  [ True False False]]

 [[ True False False]
  [ True  True  True]]], shape=(2, 2, 3), dtype=bool)
tf.Tensor(
[[False False]
 [False  True]], shape=(2, 2), dtype=bool)
